
CREATE TABLE ACTIVE_CHAT (
 ID BIGSERIAL PRIMARY KEY NOT NULL,
 CHAT_ID INTEGER NOT NULL
);

CREATE TABLE INCOMES (
 ID BIGSERIAL PRIMARY KEY NOT NULL,
 CHAT_ID INTEGER NOT NULL,
 INCOME INTEGER
);

CREATE TABLE SPEND (
 ID BIGSERIAL PRIMARY KEY NOT NULL,
 CHAT_ID INTEGER NOT NULL,
 SPEND INTEGER
);

